
export enum TypeKeys {
    CREATE_LANE = "CREATE_LANE",
    UPDATE_LANE = "UPDATE_LANE",
    DELETE_LANE = "DELETE_LANE",
    ATTACH_TO_LANE = "ATTACH_TO_LANE",
    DETACH_FROM_LANE = "DETACH_FROM_LANE",
    MOVE = "MOVE",
    CREATE_NOTE = "CREATE_NOTE",
    UPDATE_NOTE = "UPDATE_NOTE",
    DELETE_NOTE = "DELETE_NOTE",

}
